<a href="https://colab.research.google.com/github/tustus1022-ui/esaa/blob/main/YB_0508_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_%ED%9A%8C%EA%B7%801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 단순 선형 회귀 분석**
- 전복의 나이를 예측하는 선형회귀모델을 생성하세요.
- 전복의 ‘성별’, ‘키’, ‘지름’, ‘높이’, ‘전체무게’, ‘몸통무게’, ‘내장무게’, ‘껍질무게’를 이용해 ‘껍질의 고리 수’를 예측한 뒤, **예측된 ‘껍질의 고리 수’에 1.5를 더하면 전복의 나이**가 됩니다.

In [1]:
# 기본 모듈 불러오기
import numpy as np
import pandas as pd

**1) 데이터 load 및 변형**

In [2]:
# 데이터 로드
data = pd.read_csv("abalone.csv")
data.head()
print(data.shape)

# 성별 M은 Male, F는 Female, I는 Infant 이므로 따로 열 만들기
for label in "MFI":
    data[label] = data["Sex"] == label
data.drop('Sex', axis=1, inplace=True)

(4177, 9)

**2) X, y 선택**
: y는 Rings열, X는 Rings열을 제외한 나머지를 선택하되 전부 실수가 되도록 한다.

In [3]:
# X,y 데이터 선택
y = data.Rings.values
data.drop('Rings',axis=1,inplace=True)

X = data.values.astype(float)

 **3) train/test set 분리**

In [4]:
# 필요한 모듈 불러오기
from sklearn.model_selection import train_test_split

In [5]:
# train과 test set 분리 (train:test = 7:3 비율로)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

**4) 선형회귀모델 생성, 모델 예측치 구하기**

In [6]:
#필요한 모듈 불러오기
from sklearn.linear_model import LinearRegression

In [8]:
#선형회귀모델 생성 및 훈련
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [9]:
# 모델 예측치 구하기
y_preds = model.predict(X_test)

# 모델 예측치를 활용해 최종적으로 전복의 나이를 예측
y_pred_age = y_preds + 1.5

**5) 모델 평가: MSE, RMSE, R2 score, corr 구하기**

In [10]:
#필요한 모듈 불러오기
from sklearn.metrics import mean_squared_error, r2_score

- MSE, RMSE

In [12]:
#mse, rmse
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print('MSE:{0:.3f}, RMSE:{1:.3f}'.format(mse, rmse))

MSE:4.928, RMSE:2.220

- R2 score

In [17]:
#R2 score 측정
print('Variance score: {0:.3f}'.format(r2_score(y_test, y_preds)))

Variance score: 0.534

- 회귀 절편값

In [16]:
#회귀 절편 값
print('절편 값:',model.intercept_)

절편 값: 3.721176389190335

- 회귀 계수 값

In [15]:
#회귀 계수 값
print('회귀 계수 값:', np.round(model.coef_,1))

회귀 계수 값: [  1.6   9.3   7.2  10.  -21.5 -10.5   7.9   0.3   0.3  -0.6]

- 상관계수

Hint: corr 함수 이용.

In [20]:
# 상관계수 구하기
df = pd.DataFrame({'y_pred' : y_preds, 'y_true' : y_test})
cor = df['y_pred'].corr(df['y_true'])
cor

np.float64(0.7307457314219017)

# **2. Polynomial features**

In [22]:
# PolynomialFeatures 라이브러리 호출
from sklearn.preprocessing import PolynomialFeatures

In [23]:
# 임의 데이터 생성

X = np.arange(6).reshape(3, 2)

df =  pd.DataFrame(X)
df.columns = ['x_1','x_2']
df

   x_1  x_2
0    0    1
1    2    3
2    4    5

In [24]:
# 차원은 2로 설정
poly_features = PolynomialFeatures(degree=2)

# fit_transform 메소드를 통해 데이터 변환
df_poly = poly_features.fit_transform(df)

# PolynomialFeatures로 변환 된 데이터를 데이터 프레임 형태로 변환
df_poly = pd.DataFrame(df_poly)

df_poly

     0    1    2     3     4     5
0  1.0  0.0  1.0   0.0   0.0   1.0
1  1.0  2.0  3.0   4.0   6.0   9.0
2  1.0  4.0  5.0  16.0  20.0  25.0

In [25]:
# df_poly의 컬럼을 1,x1,x2,x1^2,x1*x2,x2^2 로 변경
df_poly.coumns = ['1','x1','x2','x1^2','x1*x2','x2^2']

df_poly

/tmp/ipykernel_8406/2338794969.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_poly.coumns = ['1','x1','x2','x1^2','x1*x2','x2^2']

     0    1    2     3     4     5
0  1.0  0.0  1.0   0.0   0.0   1.0
1  1.0  2.0  3.0   4.0   6.0   9.0
2  1.0  4.0  5.0  16.0  20.0  25.0